<?php
/*
	Blog Post by Jackson Siro
	https://github.com/JacksiroKe/Q2A-Blog-Post-Plugin

	Description: Blog Post Plugin Language phrases

*/

if (!defined('QA_VERSION')) { // don't allow this page to be requested directly from browser
	header('Location: ../../../');
	exit;
}

	return array(
		'1_blogpost' => '1 article',	
		'add_cat_button' => 'Add a Blog Post Category',	
		'add_p_favorites' => 'Add this post to my favorites',	
		'all_posts' => 'All',		
		'answer_must_be_approved' => 'Your account must be approved before you comment on a post. Please wait or ^1add more information^2.',	
		'article_avatar' => 'Size of Author\'s Avatar in article page',	
		'article_avatar_suffix' => ' px',
		'article_not_found' => 'Article not Found!',
		'article_not_found_page' => "Oops! The article you are trying to view could not be found. It could be hidden, deleted or unavailable at the moment. \n\nPlease go back to the previous page and try to navigate to the correct article. We regret for any inconvinience caused.",
		'articles_by_x' => 'Articles by ^',
		'approve_a_popup' => 'Approve this comment',
		'approve_button' => 'approve',
		'approve_c_popup' => 'Approve this reply',
		'approve_p_popup' => 'Approve this article',
		'articles_by_x' => 'Articles by ^',
		'blog_permissions' => 'Blog Post Permissions',	
		'blog_post' => 'Blog Post: ',	
		'blog_save' => 'Blog Settings have been saved!',	
		'blogcat_label' => 'Select a Category',	
		'blogger_info' => 'Default information about a blogger',	
		'blogger_info_descr' => 'If a blogger has not updated the about me section of his/her profile then this text will show on the article page instead of blank space . . .',
		'bp_allow_no_blogcat' => 'Allow articles with no category',	
		'bp_allow_no_sub_blogcat' => 'Allow articles with a category but no sub-category ',
		'bp_avatar_size_comment' => 'Size of Commenter\'s Avatar',	
		'bp_avatar_size_home' => 'Size of Author\'s Avatar in Blog home page',	
		'bp_blog_editor' => 'Default editor for Posting Articles',	
		'bp_blog_rules' => 'Instructions on the Posting page. HTML Allowed (Optional)',	
		'bp_blog_tagline' => 'Blog Tagline HTML allowed (Optional)',	
		'bp_blog_title' => 'Blog Title (Optional)',
		'bp_categories' => 'Blog Post Categories',
		'bp_moderate' => 'Blog Post Moderation',
		'bp_settings' => 'Blog Post Settings',
		'bp_content_max' => 'Maximum length of content preview',	
		'bp_nof_comments' => 'Number of Comments per article page',	
		'bp_nof_home_articles' => 'Number of Articles per page',	
		'bp_permit_delete_hidden' => 'Deleting hidden posts',	
		'bp_permit_delete_hidden' => 'Deleting hidden posts',	
		'bp_permit_flag' => 'Flagging posts',	
		'bp_permit_hide_show' => 'Hiding or showing any post',	
		'bp_permit_moderate' => 'Approving or rejecting posts',	
		'bp_permit_post_c' => 'Adding comments',	
		'bp_permit_post_p' => 'Writing articles',	
		'bp_permit_view_p_page' => 'Viewing articles',	
		'bp_permit_vote' => 'Voting on articles and comments',	
		'cancel_button' => 'Cancel',	
		'categories_introduction' => 'To get started with article categories, click the \'Add a Blog Post Category\' button.',	
		'category_none_error' => '^q article/s currently have no category - ^1set category^2',
		'category_write_not_allowed' => 'You do not have permission to write articles in this category',
		'claim_a_popup' => 'Assign this comment to your user account',
		'claim_button' => 'I wrote this',
		'claim_c_popup' => 'Assign this comment to your user account',
		'claim_p_popup' => 'Assign this article to your user account',
		'clear_flags_button' => 'clear flags',
		'clear_flags_popup' => 'Remove flags by all users',
		'close_button' => 'close',
		'close_p_popup' => 'Close this article to any new comment',
		'closed_as_duplicate' => 'closed as a duplicate of:',
		'closed_with_note' => 'closed with the note:',	
		'comment_avatar_suffix' => ' px',
		'comment_button' => 'Comment',
		'comment_must_confirm' => 'Please ^5confirm your email address^6 to comment on this post.',	
		'comment_must_login' => 'Please ^1log in^2 or ^3register^4 to comment on this post.',	
	    'comment_p_popup' => 'Add a comment on this article',
		'comments' => ' Comments',	
		'comments_no' => ' Comments ',	
		'content_label' => 'Content for your article goes here',	
		'default_blog_rules' => 'Your articles are viewable by you and other site visitors to your profile and in the blog. You can post new content using the form below',	
		'default_blog_tagline' => 'These posts are made by members on this website. You can make some yourself!',	
		'default_blog_title' => 'My QtoA Blog',	
		'delete_a_popup' => 'Delete this answer permanently',
		'delete_button' => 'delete',
		'delete_c_popup' => 'Delete this comment permanently',
		'delete_cat_reassign' => 'Delete this category and reassign its articles to:',	
		'delete_p_popup' => 'Delete this article permanently',
		'draft_button' => 'Save as a Draft',
		'edit_button' => 'edit',
		'edit_p_popup' => 'Edit this article',			
		'enable_plugin' => 'Enable the Blog Post Plugin',	
		'enable_widget' => 'Show Blog Latest Widget Title',
		'flag_hide_button' => 'flag and hide',	
		'flag_p_popup' => 'Flag this article as spam or inappropriate',
		'follows_a' => 'related to an answer for:',
		'follows_p' => 'about the article:',
		'hide_a_popup' => 'Hide this comment',
		'hide_button' => 'hide',
		'hide_c_popup' => 'Hide this reply',
		'hide_p_popup' => 'Hide this article',
		'home_avatar_suffix' => ' px',	
		'in' => ' in ',	
		'moderation_title' => 'Blog Post Moderation',	
		'nav_activity' => 'All Activity',	
		'nav_all' => 'All Articles',	
		'nav_articles' => 'All Articles',
		'nav_categories' => 'Blog Categories',	
		'nav_moderate' => 'Blog Moderation',
		'nav_post' => 'New Article',
		'nav_settings' => 'Blog Settings',	
		'nav_user' => 'User ',	
		'nav_wall' => 'Wall',	
		'new_articles' => 'New Article',
		'no_articles_by_x' => 'No articles by ^',
		'no_articles_found' => 'No Articles found',	
		'no_post' => 'hasn\'t posted any articles yet',
		'oops' => 'Oops! It looks like',
		'p_hidden_author' => 'This article has been hidden by its author',
		'p_hidden_flagged' => 'This article has been flagged and hidden',
		'p_hidden_other' => 'This article has been hidden',
		'p_notify_email' => 'Email me at this address if my post is commented on:',	
		'p_notify_label' => 'Email me if my post is commented on',	
		'p_notify_x_label' => 'Email me (^) if my post is commented on',	
		'p_tags_comma_label' => 'Tags - use comma (,) as a separator:',
		'p_tags_label' => 'Tags - use hyphens to combine words:',
		'p_title_label' => 'The article in one sentence:',
		'p_waiting_approval' => 'This article is waiting for approval',
		'p_waiting_your_approval' => 'This article is waiting for your approval',
		'p_your_waiting_approval' => 'Your article will be checked and approved shortly.',
		'post_button' => 'Publish Your Article',
		'posted' => 'Published',
		'recat_button' => 'recategorize',
		'recat_popup' => 'Change this article\'s category',
		'recat_p_title' => 'Recategorize article',
		'recent_ps_title' => 'Recent Articles',
		'reject_a_popup' => 'Reject this comment',
		'reject_button' => 'reject',
		'reject_c_popup' => 'Reject this reply',
		'reject_p_popup' => 'Reject this article',
		'reopen_button' => 'reopen',
		'reply_button' => 'reply',
		'reply_c_popup' => 'Reply to this comment',
		'reply_p_popup' => 'Reply to this article',
		'reshow_a_popup' => 'Reshow this answer',
		'reshow_button' => 'reshow',
		'reshow_c_popup' => 'Reshow this comment',
		'reshow_p_popup' => 'Reshow this article',
		'reopen_p_popup' => 'Reopen this article',
		'suffix_bp_avatar_size_comment' => 'px',
		'suffix_bp_avatar_size_home' => 'px',		
		'suffix_bp_avatar_size_home' => 'px',	
		'suffix_bp_content_max' => 'characters on your blog\'s homepage',	
		'suffix_bp_nof_comments' => '',
		'suffix_bp_nof_home_articles' => '',
		'suggest_category_ps' => 'To see more, click for all the ^1articles in this category^2.',	
		'suggest_ps' => 'To see more, click for the ^1full list of articles^2.',	
		'suggest_ps_tags' => 'To see more, click for the ^1full list of articles^2 or ^3popular tags^4.',	
		'suggest_write' => 'Help get things started by ^1writing an article^2.',	
		'tagline_scrol'	=> 'Display a scrolling tagline',
		'title_label' => 'Title for your Article',	
		'title_recent' => 'Recent articles by ',	
		'top_level_categories' => 'Top level article categories:',	
		'total_ps' => 'Total Blog Posts',
		'unflag_button' => 'unflag',
		'unflag_popup' => 'Remove the flag that you added',
		'view_p_must_be_approved' => 'Your account must be approved to view blog pages. Please wait or ^1add more information^2.',
		'view_p_must_confirm' => 'Please ^5confirm your email address^6 to view blog pages.',
		'view_p_must_login' => 'Please ^1log in^2 or ^3register^4 to view blog pages.',	
		'write_article' => 'Write an Article',	
		'write_limit' => 'Too many article received - please try again in an hour',	
		'write_must_be_approved' => 'Your account must be approved before you write an article. Please wait or ^1add more information^2.',	
		'write_must_confirm' => 'Please ^5confirm your email address^6 to write an article.',	
		'write_must_login' => 'Please ^1log in^2 or ^3register^4 to write an article.',	
		'write_same_p' => 'Before proceeding, please check your article was not posted already:',	
		'written_by' => ' Written by ',	
		'written_on' => 'Written on ',	
		'x_blogposts' => '^ articles',
	);

/*
	Omit PHP closing tag to help avoid accidental output
*/
